{% set version = "1.7" %}
{% set sha256 = "b2d55be869c4f716084a19b1e16932f0769711316ba62de941320bf2be84763d" %}

package:
  name: scandir
  version: {{ version }}

source:
  fn: scandir-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scandir/scandir-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - scandir

about:
  home: https://github.com/benhoyt/scandir
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'scandir, a better directory iterator and faster os.walk()'

extra:
  recipe-maintainers:
    - kain88-de
    - dotsdl
