{% set version = "1.10.0" %}
{% set sha256 = "4d4631f6062e658e9007ab3149a9b914f3548cb38bfb021c64f39a025ce578ae" %}

package:
  name: scandir
  version: {{ version }}

source:
  fn: scandir-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scandir/scandir-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 8
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - scandir

about:
  home: https://github.com/benhoyt/scandir
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'scandir, a better directory iterator and faster os.walk()'

extra:
  recipe-maintainers:
    - jan-janssen
    - kain88-de
    - dotsdl
