travis:
  secure:
    BINSTAR_TOKEN: S3GiDzPuGeng272jK4BN/L59s742jdf8A3QnWLViqvzyBWRdloh1tOpB7bEZNpttzocxMfoo2fvLPAUM7T50czBYHWSg9Zn7ZvwY9+qLCUlBLTv5et9ysnyEdtREkecfJ4AVegimnbVyhhkAAg/fbpHGuIQZbJP2TvXleqO/5Iqop4DTkN6L7F/4acSJNqPLYGlntnsVeIuIaHLkreOtf8zYPJD3USynwlMcoi/3FQ7ADkEd8ye4Xp7aAEKlwO3yW/SkcQG5TkkCkA6IZM2T1LanijURPACHM3ejZwS3+DviC+AHYR0bGOlJWj0KLjmvBzplswAQWynwMQSKmFfD5FEy4x/Ubk8Y7wf9uUX2sy8SE+EVSM0M4SVVTlxJHR7tTe6TUv55zRb6FBXPkCN8vgpNM9j2wwWtG2zUJbMlqV0sInPCq4/D3+3ZtQkv4JZmdUDMmaaEKyBFvlzHPX5DCUUk0LqMuMHVIL9lNz/JSCQdLCLPbrv8Sv6Tcf6wljHS2iQwpzaR+/v8CGoqYYF/rAmuNYBghbhj/nCfqk5jlSh/lqnge4JPn/+bDaki/pDbXBOrBYBjNt6+H2ZvKtJmKj3mcAPS61K3ZEdT9pF6IafPP9T6llIwYJ4kuRiGjAv9HX7TjcTmx4nx8Nnr0T472hxEV/Nln3WDu9qkyrdQwA4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
